type Lead = {
  id: string;
  name: string;
  businessType: string;
  primaryIndustry: string;
  niche: string;
  serviceAvailability: string;
  onlineService: "Yes" | "No";
  country: string;
  city: string;
};

export const DUMMY_LEADS: Lead[] = [
  {
    id: "1",
    name: "TechNova Solutions",
    businessType: "software-company",
    primaryIndustry: "saas",
    niche: "AI Automation Tools",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "bangladesh",
    city: "Dhaka",
  },
  {
    id: "2",
    name: "FreshRoute Foods",
    businessType: "supplier",
    primaryIndustry: "food-distribution",
    niche: "Perishable Delivery",
    serviceAvailability: "Local",
    onlineService: "No",
    country: "india",
    city: "Mumbai",
  },
  {
    id: "3",
    name: "StyleNest Fashion",
    businessType: "ecommerce-store",
    primaryIndustry: "fashion",
    niche: "Women Apparel",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "uae",
    city: "Dubai",
  },
  {
    id: "4",
    name: "CodeBridge Labs",
    businessType: "it-agency",
    primaryIndustry: "software-services",
    niche: "Web App Development",
    serviceAvailability: "International",
    onlineService: "Yes",
    country: "srilanka",
    city: "Colombo",
  },
  {
    id: "5",
    name: "BluePeak Retail Systems",
    businessType: "retail-tech",
    primaryIndustry: "retail",
    niche: "POS & Inventory Software",
    serviceAvailability: "Regional",
    onlineService: "Yes",
    country: "india",
    city: "Bangalore",
  },

  // --- START 35 NEW LEADS BASED ON FILTER LISTS ---

  {
    id: "6",
    name: "GreenHarvest Supplies",
    businessType: "supplier",
    primaryIndustry: "agriculture",
    niche: "Organic Farming Supply",
    serviceAvailability: "Local",
    onlineService: "No",
    country: "bangladesh",
    city: "Rajshahi",
  },
  {
    id: "7",
    name: "CloudCore Technologies",
    businessType: "software-company",
    primaryIndustry: "saas",
    niche: "Cloud Storage",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "singapore",
    city: "Singapore",
  },
  {
    id: "8",
    name: "UrbanEdge Apparel",
    businessType: "ecommerce-store",
    primaryIndustry: "fashion",
    niche: "Streetwear",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "usa",
    city: "Los Angeles",
  },
  {
    id: "9",
    name: "HealthLink Diagnostics",
    businessType: "health-services",
    primaryIndustry: "medical",
    niche: "Diagnostics Lab",
    serviceAvailability: "Regional",
    onlineService: "No",
    country: "india",
    city: "Delhi",
  },
  {
    id: "10",
    name: "BrightWave Digital",
    businessType: "it-agency",
    primaryIndustry: "marketing-services",
    niche: "SEO Agency",
    serviceAvailability: "International",
    onlineService: "Yes",
    country: "pakistan",
    city: "Karachi",
  },
  {
    id: "11",
    name: "PrimeLogix Freight",
    businessType: "logistics",
    primaryIndustry: "transport",
    niche: "Global Cargo",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "uae",
    city: "Sharjah",
  },
  {
    id: "12",
    name: "Zenith Learning Hub",
    businessType: "education-service",
    primaryIndustry: "e-learning",
    niche: "Leadership Training",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "india",
    city: "Pune",
  },
  {
    id: "13",
    name: "EcoScents Candle Co.",
    businessType: "supplier",
    primaryIndustry: "lifestyle",
    niche: "Handmade Candles",
    serviceAvailability: "Local",
    onlineService: "No",
    country: "bangladesh",
    city: "Chittagong",
  },
  {
    id: "14",
    name: "AromaBite Kitchens",
    businessType: "supplier",
    primaryIndustry: "food-distribution",
    niche: "Hotel Ingredient Supply",
    serviceAvailability: "Regional",
    onlineService: "No",
    country: "india",
    city: "Chennai",
  },
  {
    id: "15",
    name: "MetaForge Software",
    businessType: "software-company",
    primaryIndustry: "saas",
    niche: "HR Automation",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "usa",
    city: "Austin",
  },
  {
    id: "16",
    name: "NextRetail Hub",
    businessType: "retail-tech",
    primaryIndustry: "retail",
    niche: "Inventory Management",
    serviceAvailability: "International",
    onlineService: "Yes",
    country: "philippines",
    city: "Manila",
  },
  {
    id: "17",
    name: "OceanFresh Exporters",
    businessType: "supplier",
    primaryIndustry: "seafood-distribution",
    niche: "Frozen Seafood Export",
    serviceAvailability: "International",
    onlineService: "No",
    country: "srilanka",
    city: "Galle",
  },
  {
    id: "18",
    name: "EliteCraft Furniture",
    businessType: "manufacturer",
    primaryIndustry: "furniture",
    niche: "Office Furniture",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "malaysia",
    city: "Kuala Lumpur",
  },
  {
    id: "19",
    name: "ShopEase Mart",
    businessType: "ecommerce-store",
    primaryIndustry: "retail",
    niche: "Daily Essentials",
    serviceAvailability: "Local",
    onlineService: "Yes",
    country: "bangladesh",
    city: "Sylhet",
  },
  {
    id: "20",
    name: "EduPro Tutors",
    businessType: "education-service",
    primaryIndustry: "e-learning",
    niche: "Online Coaching",
    serviceAvailability: "International",
    onlineService: "Yes",
    country: "india",
    city: "Hyderabad",
  },
  {
    id: "21",
    name: "SnapPrint Studios",
    businessType: "printing-agency",
    primaryIndustry: "creative-services",
    niche: "Branding & Print",
    serviceAvailability: "Local",
    onlineService: "No",
    country: "uae",
    city: "Abu Dhabi",
  },
  {
    id: "22",
    name: "FoodFlow Logistics",
    businessType: "logistics",
    primaryIndustry: "cold-storage",
    niche: "Cold Chain Supply",
    serviceAvailability: "Regional",
    onlineService: "Yes",
    country: "india",
    city: "Lucknow",
  },
  {
    id: "23",
    name: "GlowNest Beauty",
    businessType: "ecommerce-store",
    primaryIndustry: "beauty",
    niche: "Organic Skincare",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "uk",
    city: "London",
  },
  {
    id: "24",
    name: "ByteWorks IT",
    businessType: "it-agency",
    primaryIndustry: "software-services",
    niche: "Mobile App Dev",
    serviceAvailability: "International",
    onlineService: "Yes",
    country: "pakistan",
    city: "Lahore",
  },
  {
    id: "25",
    name: "GoldenGrain Mills",
    businessType: "supplier",
    primaryIndustry: "food-distribution",
    niche: "Grain Supply",
    serviceAvailability: "Regional",
    onlineService: "No",
    country: "bangladesh",
    city: "Khulna",
  },
  {
    id: "26",
    name: "Skyline Media House",
    businessType: "marketing-agency",
    primaryIndustry: "creative-services",
    niche: "Ad Campaigns",
    serviceAvailability: "Global",
    onlineService: "Yes",
    country: "uae",
    city: "Dubai",
  },
  {
    id: "27",
    name: "RoboLab Innovations",
    businessType: "software-company",
    primaryIndustry: "robotics",
    niche: "Automation Systems",
    serviceAvailability: "International",
    onlineService: "Yes",
    country: "japan",
    city: "Tokyo",
  },
  {
    id: "28",
    name: "UrbanFresh Organics",
    businessType: "supplier",
    primaryIndustry: "agriculture",
    niche: "Organic Veggies",
    serviceAvailability: "Local",
    onlineService: "No",
    country: "india",
    city: "Kochi",
  },
  {
    id: "29",
    name: "TravelLink Advisors",
    businessType: "travel-agency",
    primaryIndustry: "tourism",
    niche: "Corporate Tours",
    serviceAvailability: "International",
    onlineService: "Yes",
    country: "uae",
    city: "Dubai",
  },
  {
    id: "30",
    name: "FitGear Pro",
    businessType: "ecommerce-store",
    primaryIndustry: "fitness",
    niche: "Gym Equipment",
    serviceAvailability: "Regional",
    onlineService: "Yes",
    country: "india",
    city: "Ahmedabad",
  },
];

export const COUNTRY_LIST = [
  { label: "Bangladesh", value: "bangladesh" },
  { label: "India", value: "india" },
  { label: "UAE", value: "uae" },
  { label: "Sri Lanka", value: "srilanka" },
  { label: "Singapore", value: "singapore" },
  { label: "USA", value: "usa" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Philippines", value: "philippines" },
  { label: "Malaysia", value: "malaysia" },
  { label: "UK", value: "uk" },
  { label: "Japan", value: "japan" },
];
export const BUSINESS_TYPE_LIST = [
  "LLC",
  "Corporation",
  "Sole Proprietorship",
  "Partnership",
];
// export const BUSINESS_TYPE_LIST = [
//   { label: "Software Company", value: "software-company" },
//   { label: "Supplier", value: "supplier" },
//   { label: "E-commerce Store", value: "ecommerce-store" },
//   { label: "IT Agency", value: "it-agency" },
//   { label: "Retail Tech", value: "retail-tech" },
//   { label: "Health Services", value: "health-services" },
//   { label: "Logistics", value: "logistics" },
//   { label: "Education Service", value: "education-service" },
//   { label: "Manufacturer", value: "manufacturer" },
//   { label: "Printing Agency", value: "printing-agency" },
//   { label: "Marketing Agency", value: "marketing-agency" },
//   { label: "Travel Agency", value: "travel-agency" },
// ];

export const INDUSTRY_LIST = [
  { label: "SaaS", value: "saas" },
  { label: "Food Distribution", value: "food-distribution" },
  { label: "Fashion", value: "fashion" },
  { label: "Software Services", value: "software-services" },
  { label: "Retail", value: "retail" },
  { label: "Agriculture", value: "agriculture" },
  { label: "Medical", value: "medical" },
  { label: "Marketing Services", value: "marketing-services" },
  { label: "Transport", value: "transport" },
  { label: "E-learning", value: "e-learning" },
  { label: "Lifestyle", value: "lifestyle" },
  { label: "Seafood Distribution", value: "seafood-distribution" },
  { label: "Furniture", value: "furniture" },
  { label: "Beauty", value: "beauty" },
  { label: "Cold Storage", value: "cold-storage" },
  { label: "Creative Services", value: "creative-services" },
  { label: "Robotics", value: "robotics" },
  { label: "Tourism", value: "tourism" },
  { label: "Fitness", value: "fitness" },
];
