export const B2C_SECTIONS = [
  {
    title: "Personal Details",
    fields: ["fullName", "nickname", "nationality", "dob", "gender"],
  },
  {
    title: "Contact & Communication",
    fields: [
      "primaryEmail",
      "secondaryEmail",
      "primaryPhone",
      "secondaryPhone",
      "whatsapp",
      "telegram",
      "wechat",
      "prefferedContactMethod",
    ],
  },
  {
    title: "Location",
    fields: [
      "country",
      "state",
      "city",
      "subCity",
      "cityCorporation",
      "street",
      "postalCode",
      "timeZone",
    ],
  },
  {
    title: "Professional Details",
    fields: [
      "currentJobTitle",
      "company",
      "workType",
      "workModel",
      "primaryIndustry",
      "industrySubsector",
      "coreResponsibilities",
      "keyTools",
    ],
  },
  {
    title: "Skills",
    fields: [
      "primarySkills",
      "secondarySkills",
      "technicalTools",
      "topSoftSkills",
      "professionalCertifications",
      "licenses",
      "credentials",
    ],
  },
  {
    title: "Career Summary",
    fields: ["totalExperience", "careerHighlight"],
  },
  {
    title: "Education & Academic",
    fields: [
      "highestDegree",
      "degreesEarned",
      "institutions",
      "fieldsOfStudy",
      "graduationDates",
      "gpa",
      "academicHonors",
      "publications",
      "researchAreas",
      "thesisTitle",
      "academicIds",
    ],
  },
  {
    title: "Personal Web Presence",
    fields: [
      "personalWebsite",
      "portfolio",
      "blog",
      "onlineResume",
      "linktree",
      "publicNotion",
    ],
  },
  {
    title: "Interests & Lifestyle",
    fields: ["interests", "lifestylePreferences"],
  },
  {
    title: "Social & Civic Activities",
    fields: [
      "organizations",
      "role",
      "activities",
      "civicEngagement",
      "policyInterests",
    ],
  },
  {
    title: "Family & Household",
    fields: [
      "maritalStatus",
      "partnerSpouse",
      "childrenDependents",
      "householdSize",
      "householdIncome",
      "familyMedicalHistory",
      "guardianshipStatus",
    ],
  },
  {
    title: "Health & Medical Information",
    fields: [
      "heightWeightBMI",
      "allergies",
      "chronicIllnesses",
      "disabilities",
      "diagnoses",
      "medications",
      "surgeries",
      "vaccinationRecords",
      "medicalDevices",
      "healthInsurance",
    ],
  },
  {
    title: "Financial Information",
    fields: [
      "salary",
      "totalIncome",
      "incomeHistory",
      "savings",
      "investments",
      "cryptocurrency",
      "loans",
      "debts",
      "bankAccounts",
      "creditScore",
      "transactionHistory",
      "insurancePolicies",
    ],
  },
  {
    title: "Legal & Government",
    fields: [
      "nationalId",
      "passport",
      "driversLicense",
      "visaWorkPermit",
      "criminalBackground",
      "courtRecords",
      "contractsSigned",
      "consentRecords",
      "taxIdentificationNumber",
    ],
  },
  {
    title: "Memberships & Affiliations",
    fields: [
      "clubs",
      "alumniGroups",
      "professionalAssociations",
      "nonprofits",
      "loyaltyPrograms",
      "volunteerActivities",
    ],
  },
];
