export type Lead = {
  id: number;
  companyName: string;
  contactName: string;
  email: string;
  phone: string;
  industry: string;
  country: string;
  status:
    | 'New'
    | 'Contacted'
    | 'In Progress'
    | 'Qualified'
    | 'Proposal Sent'
    | 'Negotiation'
    | 'Won'
    | 'Lost';
};

export const leadsData: Lead[] = [
  {
    id: 1,
    companyName: 'TechCorp',
    contactName: 'John Doe',
    email: 'john@techcorp.com',
    phone: '+1-555-1234',
    industry: 'IT',
    country: 'USA',
    status: 'New',
  },
  {
    id: 2,
    companyName: 'HealthPlus',
    contactName: 'Jane Smith',
    email: 'jane@healthplus.com',
    phone: '+1-555-5678',
    industry: 'Healthcare',
    country: 'UK',
    status: 'Contacted',
  },

  // ---- NEW DATA BELOW ---- //

  {
    id: 3,
    companyName: 'BlueWave Solutions',
    contactName: 'Michael Carter',
    email: 'michael@bluewave.com',
    phone: '+1-202-4321',
    industry: 'Software',
    country: 'USA',
    status: 'Qualified',
  },
  {
    id: 4,
    companyName: 'GreenLeaf Farms',
    contactName: 'Alicia Brown',
    email: 'alicia@greenleaf.com',
    phone: '+44-7700-123456',
    industry: 'Agriculture',
    country: 'UK',
    status: 'New',
  },
  {
    id: 5,
    companyName: 'NovaTech',
    contactName: 'Samuel Lee',
    email: 'samuel@novatech.io',
    phone: '+1-312-7788',
    industry: 'IT',
    country: 'Canada',
    status: 'Contacted',
  },
  {
    id: 6,
    companyName: 'Skyline Logistics',
    contactName: 'Emily Davis',
    email: 'emily@skyline-log.com',
    phone: '+61-400-987-654',
    industry: 'Logistics',
    country: 'Australia',
    status: 'New',
  },
  {
    id: 7,
    companyName: 'BrightMind Education',
    contactName: 'Daniel Wilson',
    email: 'daniel@brightmind.edu',
    phone: '+91-8800-220011',
    industry: 'Education',
    country: 'India',
    status: 'Qualified',
  },
  {
    id: 8,
    companyName: 'GlobalFoods',
    contactName: 'Sophia Martinez',
    email: 'sophia@globalfoods.org',
    phone: '+34-600-765-432',
    industry: 'Food & Beverage',
    country: 'Spain',
    status: 'Contacted',
  },
  {
    id: 9,
    companyName: 'UrbanStyle Fashion',
    contactName: 'Robert Clark',
    email: 'robert@urbanstyle.co',
    phone: '+49-160-223344',
    industry: 'Fashion',
    country: 'Germany',
    status: 'New',
  },
  {
    id: 10,
    companyName: 'FinTrust Bank',
    contactName: 'Emma Thompson',
    email: 'emma@fintrustbank.com',
    phone: '+1-888-900-1122',
    industry: 'Finance',
    country: 'USA',
    status: 'Lost',
  },
  {
    id: 11,
    companyName: 'MediCare Labs',
    contactName: 'Liam Anderson',
    email: 'liam@medicarelabs.org',
    phone: '+1-777-432-9001',
    industry: 'Healthcare',
    country: 'USA',
    status: 'Contacted',
  },
  {
    id: 12,
    companyName: 'EcoBuild Construction',
    contactName: 'Olivia Nguyen',
    email: 'olivia@ecobuild.com',
    phone: '+61-422-101-999',
    industry: 'Construction',
    country: 'Australia',
    status: 'Qualified',
  },
  {
    id: 13,
    companyName: 'PixelPeak Media',
    contactName: 'Jacob Walker',
    email: 'jacob@pixelpeak.media',
    phone: '+1-222-9900',
    industry: 'Marketing',
    country: 'USA',
    status: 'New',
  },
  {
    id: 14,
    companyName: 'AquaPure Water',
    contactName: 'Charlotte Perez',
    email: 'charlotte@aquapure.com',
    phone: '+55-21-90000-2222',
    industry: 'Manufacturing',
    country: 'Brazil',
    status: 'Contacted',
  },
  {
    id: 15,
    companyName: 'Silverline Security',
    contactName: 'David Harris',
    email: 'david@silverline-sec.com',
    phone: '+1-914-220-3300',
    industry: 'Security',
    country: 'USA',
    status: 'New',
  },
  {
    id: 16,
    companyName: 'EduSmart Academy',
    contactName: 'Grace Stewart',
    email: 'grace@edusmart.ac',
    phone: '+91-8899-102030',
    industry: 'Education',
    country: 'India',
    status: 'Qualified',
  },
  {
    id: 17,
    companyName: 'FreshHarvest',
    contactName: 'James Parker',
    email: 'james@freshharvest.org',
    phone: '+33-650-123-789',
    industry: 'Food & Beverage',
    country: 'France',
    status: 'Contacted',
  },
  {
    id: 18,
    companyName: 'MetroTech Solutions',
    contactName: 'Mia Wright',
    email: 'mia@metrotech.io',
    phone: '+1-646-555-9200',
    industry: 'IT',
    country: 'USA',
    status: 'New',
  },
  {
    id: 19,
    companyName: 'Infinity Studios',
    contactName: 'Ethan Green',
    email: 'ethan@infinitystudios.tv',
    phone: '+44-20-8800-1234',
    industry: 'Media',
    country: 'UK',
    status: 'Lost',
  },
  {
    id: 20,
    companyName: 'Prime Logistics',
    contactName: 'Ava Robinson',
    email: 'ava@primelogistics.co',
    phone: '+1-505-900-7654',
    industry: 'Logistics',
    country: 'USA',
    status: 'Qualified',
  },

  {
    id: 21,
    companyName: 'NextGen Motors',
    contactName: 'Henry Collins',
    email: 'henry@nextgenmotors.com',
    phone: '+81-90-1234-5678',
    industry: 'Automotive',
    country: 'Japan',
    status: 'New',
  },
  {
    id: 22,
    companyName: 'SigmaSoft',
    contactName: 'Chloe Turner',
    email: 'chloe@sigmasoft.io',
    phone: '+1-330-4400',
    industry: 'Software',
    country: 'Canada',
    status: 'Contacted',
  },
  {
    id: 23,
    companyName: 'VitalHealth Pharma',
    contactName: 'Ryan King',
    email: 'ryan@vitalhealthpharma.com',
    phone: '+1-222-6600',
    industry: 'Healthcare',
    country: 'USA',
    status: 'Contacted',
  },
  {
    id: 24,
    companyName: 'EcoDrive Transport',
    contactName: 'Scarlett Diaz',
    email: 'scarlett@ecodrive.co',
    phone: '+34-699-123-888',
    industry: 'Transport',
    country: 'Spain',
    status: 'New',
  },
  {
    id: 25,
    companyName: 'BrightStar Energy',
    contactName: 'Nathan Brooks',
    email: 'nathan@brightstar.energy',
    phone: '+61-430-230-430',
    industry: 'Energy',
    country: 'Australia',
    status: 'Qualified',
  },
  {
    id: 26,
    companyName: 'CleanAir Filters',
    contactName: 'Avery Hughes',
    email: 'avery@cleanairfilters.com',
    phone: '+44-7400-552299',
    industry: 'Manufacturing',
    country: 'UK',
    status: 'Contacted',
  },
  {
    id: 27,
    companyName: 'SoftNest Tech',
    contactName: 'Leo Mitchell',
    email: 'leo@softnesttech.com',
    phone: '+1-989-2211',
    industry: 'IT',
    country: 'USA',
    status: 'New',
  },
  {
    id: 28,
    companyName: 'UrbanCafe',
    contactName: 'Layla Richardson',
    email: 'layla@urbancafe.org',
    phone: '+33-660-998-221',
    industry: 'Food & Beverage',
    country: 'France',
    status: 'Qualified',
  },
  {
    id: 29,
    companyName: 'ProBuild Engineering',
    contactName: 'Julian Foster',
    email: 'julian@probuild-eng.com',
    phone: '+1-702-555-1123',
    industry: 'Engineering',
    country: 'USA',
    status: 'New',
  },
  {
    id: 30,
    companyName: 'CloudLink',
    contactName: 'Hazel Murphy',
    email: 'hazel@cloudlink.net',
    phone: '+1-482-1199',
    industry: 'IT',
    country: 'USA',
    status: 'Contacted',
  },

  {
    id: 31,
    companyName: 'Sunrise Hotels',
    contactName: 'Miles Griffin',
    email: 'miles@sunrisehotels.com',
    phone: '+971-55-300-2000',
    industry: 'Hospitality',
    country: 'UAE',
    status: 'New',
  },
  {
    id: 32,
    companyName: 'FoodLand Export',
    contactName: 'Nora Bennett',
    email: 'nora@foodlandexp.com',
    phone: '+1-208-8801',
    industry: 'Export',
    country: 'USA',
    status: 'Qualified',
  },
  {
    id: 33,
    companyName: 'SmartCare',
    contactName: 'Lucas Hayes',
    email: 'lucas@smartcare.app',
    phone: '+91-9900-554433',
    industry: 'Healthcare Tech',
    country: 'India',
    status: 'Won',
  },
  {
    id: 34,
    companyName: 'MegaBuild Retail',
    contactName: 'Violet Cooper',
    email: 'violet@megabuildretail.com',
    phone: '+44-20-7000-2211',
    industry: 'Retail',
    country: 'UK',
    status: 'Lost',
  },
  {
    id: 35,
    companyName: 'UniSoft Labs',
    contactName: 'Adam Price',
    email: 'adam@unisoftlabs.io',
    phone: '+1-320-5566',
    industry: 'Software',
    country: 'USA',
    status: 'New',
  },
  {
    id: 36,
    companyName: 'GreenPetro Fuels',
    contactName: 'Anna Rivera',
    email: 'anna@greenpetro.energy',
    phone: '+55-11-8900-5566',
    industry: 'Energy',
    country: 'Brazil',
    status: 'Contacted',
  },
  {
    id: 37,
    companyName: 'CloudMatrix',
    contactName: 'Evan Foster',
    email: 'evan@cloudmatrix.io',
    phone: '+1-221-3300',
    industry: 'Cloud Services',
    country: 'USA',
    status: 'Qualified',
  },
  {
    id: 38,
    companyName: 'PrimeMarket Foods',
    contactName: 'Luna Jenkins',
    email: 'luna@primemarketfoods.com',
    phone: '+33-620-333-990',
    industry: 'Food & Beverage',
    country: 'France',
    status: 'Contacted',
  },
  {
    id: 39,
    companyName: 'TransAct Finance',
    contactName: 'Owen Matthews',
    email: 'owen@transactfinance.com',
    phone: '+1-601-7811',
    industry: 'Finance',
    country: 'USA',
    status: 'New',
  },
  {
    id: 40,
    companyName: 'AeroFly Systems',
    contactName: 'Ella Scott',
    email: 'ella@aeroflysys.com',
    phone: '+61-490-888-777',
    industry: 'Aviation',
    country: 'Australia',
    status: 'Qualified',
  },

  {
    id: 41,
    companyName: 'AgroWorld',
    contactName: 'Isaac Hill',
    email: 'isaac@agroworld.com',
    phone: '+91-8800-120033',
    industry: 'Agriculture',
    country: 'India',
    status: 'New',
  },
  {
    id: 42,
    companyName: 'ZenithPay',
    contactName: 'Harper Adams',
    email: 'harper@zenithpay.io',
    phone: '+1-415-900-3344',
    industry: 'FinTech',
    country: 'USA',
    status: 'Qualified',
  },
  {
    id: 43,
    companyName: 'MetroFoods',
    contactName: 'Noah Phillips',
    email: 'noah@metrofoods.org',
    phone: '+55-21-7888-2233',
    industry: 'Food & Beverage',
    country: 'Brazil',
    status: 'Lost',
  },
  {
    id: 44,
    companyName: 'SmartLink Telecom',
    contactName: 'Zoe Kelly',
    email: 'zoe@smartlinktel.com',
    phone: '+1-602-4400',
    industry: 'Telecom',
    country: 'USA',
    status: 'New',
  },
  {
    id: 45,
    companyName: 'AutoCraft Engineering',
    contactName: 'Logan Ward',
    email: 'logan@autocrafteng.com',
    phone: '+49-170-990099',
    industry: 'Automotive',
    country: 'Germany',
    status: 'Contacted',
  },
  {
    id: 46,
    companyName: 'MetaServe IT',
    contactName: 'Paisley Russell',
    email: 'paisley@metaserveit.com',
    phone: '+1-778-2100',
    industry: 'IT',
    country: 'Canada',
    status: 'Contacted',
  },
  {
    id: 47,
    companyName: 'DailyFresh Mart',
    contactName: 'Caleb Howard',
    email: 'caleb@dailyfreshmart.co',
    phone: '+971-52-800-4433',
    industry: 'Retail',
    country: 'UAE',
    status: 'New',
  },
  {
    id: 48,
    companyName: 'BuildRight Construction',
    contactName: 'Eleanor Gray',
    email: 'eleanor@buildright.co',
    phone: '+1-209-4311',
    industry: 'Construction',
    country: 'USA',
    status: 'Qualified',
  },
  {
    id: 49,
    companyName: 'InnovaSoft Labs',
    contactName: 'Christian Stewart',
    email: 'christian@innovasoftlabs.com',
    phone: '+1-617-7554',
    industry: 'Software',
    country: 'USA',
    status: 'Proposal Sent',
  },
  {
    id: 50,
    companyName: 'RoyalTaste Foods',
    contactName: 'Penelope Simmons',
    email: 'penelope@royaltastefoods.com',
    phone: '+44-7500-881199',
    industry: 'Food & Beverage',
    country: 'UK',
    status: 'Lost',
  },

  {
    id: 51,
    companyName: 'StarEdge Media',
    contactName: 'Ian Brooks',
    email: 'ian@staredgemedia.com',
    phone: '+1-888-1200',
    industry: 'Media',
    country: 'USA',
    status: 'New',
  },
  {
    id: 52,
    companyName: 'CoreLogic AI',
    contactName: 'Madison Flores',
    email: 'madison@corelogic.ai',
    phone: '+1-403-5000',
    industry: 'AI & ML',
    country: 'Canada',
    status: 'Qualified',
  },
  {
    id: 53,
    companyName: 'FreshMart Grocery',
    contactName: 'Wyatt Parker',
    email: 'wyatt@freshmart.org',
    phone: '+61-450-120-550',
    industry: 'Retail',
    country: 'Australia',
    status: 'Contacted',
  },
  {
    id: 54,
    companyName: 'TechMint',
    contactName: 'Ariana Collins',
    email: 'ariana@techmint.dev',
    phone: '+1-221-9988',
    industry: 'Software',
    country: 'USA',
    status: 'Proposal Sent',
  },
  {
    id: 55,
    companyName: 'MediCore Diagnostics',
    contactName: 'Brayden Cox',
    email: 'brayden@medicore.org',
    phone: '+44-7700-443322',
    industry: 'Healthcare',
    country: 'UK',
    status: 'Lost',
  },
  {
    id: 56,
    companyName: 'OceanBlue Exports',
    contactName: 'Lily Ramirez',
    email: 'lily@oceanblueexp.com',
    phone: '+33-660-770-881',
    industry: 'Export',
    country: 'France',
    status: 'Qualified',
  },
  {
    id: 57,
    companyName: 'DeltaCloud Systems',
    contactName: 'Bentley Foster',
    email: 'bentley@deltacloudsys.com',
    phone: '+1-505-778-990',
    industry: 'Cloud Services',
    country: 'USA',
    status: 'New',
  },
  {
    id: 58,
    companyName: 'NexaEnergy',
    contactName: 'Bella West',
    email: 'bella@nexaenergy.co',
    phone: '+55-11-5566-1144',
    industry: 'Energy',
    country: 'Brazil',
    status: 'Contacted',
  },
  {
    id: 59,
    companyName: 'TechSphere',
    contactName: 'Gavin Watson',
    email: 'gavin@techsphere.io',
    phone: '+1-301-654-2200',
    industry: 'Software',
    country: 'USA',
    status: 'Qualified',
  },
  {
    id: 60,
    companyName: 'AlphaFoods',
    contactName: 'Naomi Bailey',
    email: 'naomi@alphafoods.org',
    phone: '+34-690-112-390',
    industry: 'Food & Beverage',
    country: 'Spain',
    status: 'New',
  },
];
