export const DUMMY_B2C_LEADS = [
  {
    id: '1',
    name: 'John Doe',
    gender: 'Male',
    nationality: 'USA',
    state: 'California',
    industry: 'Technology',
    subSector: 'Software',
    skills: 'JavaScript, React',
    highestDegree: 'Bachelor',
    hobbies: 'Reading, Cycling',
    organizations: 'Google',
    maritalStatus: 'Single',
    income: '$80k - $100k',
    salary: '$90k',
  },
  {
    id: '2',
    name: 'Sara Ali',
    gender: 'Female',
    nationality: 'Bangladesh',
    state: 'Dhaka',
    industry: 'Design',
    subSector: 'UI/UX',
    skills: 'Figma, Adobe',
    highestDegree: 'Masters',
    hobbies: 'Drawing, Travel',
    organizations: 'Pathao',
    maritalStatus: 'Married',
    income: '$20k - $30k',
    salary: '$25k',
  },
  {
    id: '3',
    name: 'Ravi Kumar',
    gender: 'Male',
    nationality: 'India',
    state: 'Karnataka',
    industry: 'Finance',
    subSector: 'Banking',
    skills: 'Excel, Accounting',
    highestDegree: 'MBA',
    hobbies: 'Cricket, Chess',
    organizations: 'ICICI Bank',
    maritalStatus: 'Single',
    income: '$15k - $25k',
    salary: '$20k',
  },
  {
    id: '4',
    name: 'Emily Carter',
    gender: 'Female',
    nationality: 'Canada',
    state: 'Ontario',
    industry: 'Healthcare',
    subSector: 'Nursing',
    skills: 'Patient Care, CPR',
    highestDegree: 'Bachelor',
    hobbies: 'Hiking, Cooking',
    organizations: 'Toronto General Hospital',
    maritalStatus: 'Single',
    income: '$50k - $65k',
    salary: '$60k',
  },
  {
    id: '5',
    name: 'Ahmed Hassan',
    gender: 'Male',
    nationality: 'Egypt',
    state: 'Cairo',
    industry: 'Engineering',
    subSector: 'Civil',
    skills: 'AutoCAD, Project Planning',
    highestDegree: 'Masters',
    hobbies: 'Swimming, History',
    organizations: 'Orascom',
    maritalStatus: 'Married',
    income: '$25k - $35k',
    salary: '$30k',
  },
  {
    id: '6',
    name: 'Sophia Martinez',
    gender: 'Female',
    nationality: 'Mexico',
    state: 'Mexico City',
    industry: 'Marketing',
    subSector: 'Digital Marketing',
    skills: 'SEO, Social Media',
    highestDegree: 'Bachelor',
    hobbies: 'Photography, Travel',
    organizations: 'Coca Cola Mexico',
    maritalStatus: 'Single',
    income: '$40k - $55k',
    salary: '$48k',
  },
  {
    id: '7',
    name: 'Liam Johnson',
    gender: 'Male',
    nationality: 'UK',
    state: 'London',
    industry: 'Technology',
    subSector: 'AI Research',
    skills: 'Python, Machine Learning',
    highestDegree: 'PhD',
    hobbies: 'Chess, Reading',
    organizations: 'DeepMind',
    maritalStatus: 'Single',
    income: '$120k - $150k',
    salary: '$130k',
  },
  {
    id: '8',
    name: 'Hiroshi Tanaka',
    gender: 'Male',
    nationality: 'Japan',
    state: 'Tokyo',
    industry: 'Manufacturing',
    subSector: 'Automotive',
    skills: 'Robotics, Quality Control',
    highestDegree: 'Bachelor',
    hobbies: 'Karate, DIY',
    organizations: 'Toyota',
    maritalStatus: 'Married',
    income: '$70k - $90k',
    salary: '$85k',
  },
  {
    id: '9',
    name: 'Mina Park',
    gender: 'Female',
    nationality: 'South Korea',
    state: 'Seoul',
    industry: 'Design',
    subSector: 'Fashion',
    skills: 'Sketching, Sewing',
    highestDegree: 'Bachelor',
    hobbies: 'K-pop Dance, Art',
    organizations: 'Samsung Fashion',
    maritalStatus: 'Single',
    income: '$35k - $45k',
    salary: '$40k',
  },
  {
    id: '10',
    name: 'Carlos Rivera',
    gender: 'Male',
    nationality: 'Colombia',
    state: 'Bogota',
    industry: 'Logistics',
    subSector: 'Supply Chain',
    skills: 'Inventory, ERP',
    highestDegree: 'Bachelor',
    hobbies: 'Soccer, Gaming',
    organizations: 'DHL',
    maritalStatus: 'Married',
    income: '$30k - $40k',
    salary: '$36k',
  },
  {
    id: '11',
    name: 'Olivia Smith',
    gender: 'Female',
    nationality: 'Australia',
    state: 'Sydney',
    industry: 'Education',
    subSector: 'Teaching',
    skills: 'Classroom Management, Writing',
    highestDegree: 'Masters',
    hobbies: 'Yoga, Books',
    organizations: 'Sydney Public School',
    maritalStatus: 'Single',
    income: '$50k - $70k',
    salary: '$62k',
  },
  {
    id: '12',
    name: 'David Wilson',
    gender: 'Male',
    nationality: 'USA',
    state: 'Texas',
    industry: 'Energy',
    subSector: 'Oil & Gas',
    skills: 'Drilling Ops, Safety',
    highestDegree: 'Bachelor',
    hobbies: 'Hunting, Fishing',
    organizations: 'ExxonMobil',
    maritalStatus: 'Married',
    income: '$90k - $110k',
    salary: '$100k',
  },
  {
    id: '13',
    name: 'Nadia Khan',
    gender: 'Female',
    nationality: 'Pakistan',
    state: 'Karachi',
    industry: 'Technology',
    subSector: 'QA',
    skills: 'Testing, Automation',
    highestDegree: 'Bachelor',
    hobbies: 'Cooking, Gardening',
    organizations: 'Systems Ltd',
    maritalStatus: 'Single',
    income: '$10k - $18k',
    salary: '$14k',
  },
  {
    id: '14',
    name: 'Victor Hugo',
    gender: 'Male',
    nationality: 'Brazil',
    state: 'Rio',
    industry: 'Sports',
    subSector: 'Coaching',
    skills: 'Training, Strategy',
    highestDegree: 'Diploma',
    hobbies: 'Football, Travel',
    organizations: 'Flamengo',
    maritalStatus: 'Married',
    income: '$20k - $35k',
    salary: '$26k',
  },
  {
    id: '15',
    name: 'Hannah Lee',
    gender: 'Female',
    nationality: 'Singapore',
    state: 'Singapore',
    industry: 'Finance',
    subSector: 'Fintech',
    skills: 'Python, Trading',
    highestDegree: 'Masters',
    hobbies: 'Piano, Reading',
    organizations: 'Grab Finance',
    maritalStatus: 'Single',
    income: '$90k - $120k',
    salary: '$110k',
  },
  {
    id: '16',
    name: 'Omar Farooq',
    gender: 'Male',
    nationality: 'UAE',
    state: 'Dubai',
    industry: 'Real Estate',
    subSector: 'Sales',
    skills: 'Negotiation, CRM',
    highestDegree: 'Bachelor',
    hobbies: 'Gym, Cars',
    organizations: 'Emaar',
    maritalStatus: 'Married',
    income: '$60k - $80k',
    salary: '$75k',
  },
  {
    id: '17',
    name: 'Julia Müller',
    gender: 'Female',
    nationality: 'Germany',
    state: 'Berlin',
    industry: 'Research',
    subSector: 'Biotech',
    skills: 'Lab Work, Analysis',
    highestDegree: 'PhD',
    hobbies: 'Reading, Hiking',
    organizations: 'BioNTech',
    maritalStatus: 'Single',
    income: '$85k - $110k',
    salary: '$95k',
  },
  {
    id: '18',
    name: 'Arjun Patel',
    gender: 'Male',
    nationality: 'India',
    state: 'Gujarat',
    industry: 'Agriculture',
    subSector: 'Farm Management',
    skills: 'Soil Testing, Irrigation',
    highestDegree: 'Diploma',
    hobbies: 'Farming, Riding',
    organizations: 'AMUL',
    maritalStatus: 'Married',
    income: '$12k - $20k',
    salary: '$16k',
  },
  {
    id: '19',
    name: 'Selin Kaya',
    gender: 'Female',
    nationality: 'Turkey',
    state: 'Istanbul',
    industry: 'Tourism',
    subSector: 'Hospitality',
    skills: 'Communication, Service',
    highestDegree: 'Bachelor',
    hobbies: 'Travel, Makeup',
    organizations: 'Hilton',
    maritalStatus: 'Single',
    income: '$18k - $26k',
    salary: '$22k',
  },
  {
    id: '20',
    name: 'Daniel Brown',
    gender: 'Male',
    nationality: 'USA',
    state: 'Florida',
    industry: 'Tech',
    subSector: 'DevOps',
    skills: 'AWS, Docker',
    highestDegree: 'Bachelor',
    hobbies: 'Surfing, Coding',
    organizations: 'Netflix',
    maritalStatus: 'Single',
    income: '$100k - $130k',
    salary: '$120k',
  },
  {
    id: '21',
    name: 'Isabella Rossi',
    gender: 'Female',
    nationality: 'Italy',
    state: 'Rome',
    industry: 'Arts',
    subSector: 'Interior Design',
    skills: 'SketchUp, Design',
    highestDegree: 'Bachelor',
    hobbies: 'Art, Travel',
    organizations: 'Rossi Interiors',
    maritalStatus: 'Married',
    income: '$30k - $40k',
    salary: '$35k',
  },
  {
    id: '22',
    name: 'Mohammed Saeed',
    gender: 'Male',
    nationality: 'Saudi Arabia',
    state: 'Riyadh',
    industry: 'Oil & Gas',
    subSector: 'Operations',
    skills: 'Safety, Machines',
    highestDegree: 'Bachelor',
    hobbies: 'Falconry, Cars',
    organizations: 'Aramco',
    maritalStatus: 'Married',
    income: '$90k - $120k',
    salary: '$105k',
  },
  {
    id: '23',
    name: 'Lucy Walker',
    gender: 'Female',
    nationality: 'UK',
    state: 'Manchester',
    industry: 'Customer Support',
    subSector: 'Service Desk',
    skills: 'Communication, CRM',
    highestDegree: 'Diploma',
    hobbies: 'Movies, Crafts',
    organizations: 'BT',
    maritalStatus: 'Single',
    income: '$25k - $32k',
    salary: '$28k',
  },
  {
    id: '24',
    name: 'Felix Meyer',
    gender: 'Male',
    nationality: 'Germany',
    state: 'Hamburg',
    industry: 'Aviation',
    subSector: 'Aircraft Maintenance',
    skills: 'Engineering, Safety',
    highestDegree: 'Bachelor',
    hobbies: 'Sailing, Reading',
    organizations: 'Lufthansa',
    maritalStatus: 'Married',
    income: '$60k - $85k',
    salary: '$78k',
  },
  {
    id: '25',
    name: 'Ayesha Noor',
    gender: 'Female',
    nationality: 'Pakistan',
    state: 'Lahore',
    industry: 'Healthcare',
    subSector: 'Pharmacy',
    skills: 'Drug Dispensing, Customer Care',
    highestDegree: 'Pharm-D',
    hobbies: 'Cooking, Reading',
    organizations: 'Servaid',
    maritalStatus: 'Single',
    income: '$12k - $18k',
    salary: '$16k',
  },
  {
    id: '26',
    name: 'Fernando Silva',
    gender: 'Male',
    nationality: 'Portugal',
    state: 'Lisbon',
    industry: 'Sports',
    subSector: 'Fitness Training',
    skills: 'Gym Training, Nutrition',
    highestDegree: 'Diploma',
    hobbies: 'Running, Soccer',
    organizations: 'FitnessFirst',
    maritalStatus: 'Single',
    income: '$20k - $28k',
    salary: '$24k',
  },
  {
    id: '27',
    name: 'Mia Chen',
    gender: 'Female',
    nationality: 'China',
    state: 'Shanghai',
    industry: 'Technology',
    subSector: 'Frontend Dev',
    skills: 'Vue.js, JavaScript',
    highestDegree: 'Bachelor',
    hobbies: 'Painting, Badminton',
    organizations: 'Alibaba',
    maritalStatus: 'Single',
    income: '$50k - $70k',
    salary: '$63k',
  },
  {
    id: '28',
    name: 'Jacob Miller',
    gender: 'Male',
    nationality: 'USA',
    state: 'New York',
    industry: 'Finance',
    subSector: 'Investment',
    skills: 'Risk Analysis, Excel',
    highestDegree: 'Masters',
    hobbies: 'Running, Chess',
    organizations: 'JP Morgan',
    maritalStatus: 'Married',
    income: '$110k - $150k',
    salary: '$135k',
  },
  {
    id: '29',
    name: 'Angelica Ruiz',
    gender: 'Female',
    nationality: 'Spain',
    state: 'Madrid',
    industry: 'Hospitality',
    subSector: 'Event Management',
    skills: 'Planning, Coordination',
    highestDegree: 'Bachelor',
    hobbies: 'Music, Travel',
    organizations: 'Eventia',
    maritalStatus: 'Single',
    income: '$25k - $35k',
    salary: '$30k',
  },
  {
    id: '30',
    name: 'Tariq Ibrahim',
    gender: 'Male',
    nationality: 'Qatar',
    state: 'Doha',
    industry: 'Construction',
    subSector: 'Project Management',
    skills: 'Leadership, AutoCAD',
    highestDegree: 'Masters',
    hobbies: 'Cars, Fitness',
    organizations: 'Qatar Construction Co.',
    maritalStatus: 'Married',
    income: '$80k - $100k',
    salary: '$92k',
  },
];

export const COUNTRY_LIST = [
  { label: 'Bangladesh', value: 'bangladesh' },
  { label: 'India', value: 'india' },
  { label: 'UAE', value: 'uae' },
  { label: 'Sri Lanka', value: 'srilanka' },
  { label: 'Singapore', value: 'singapore' },
  { label: 'USA', value: 'usa' },
  { label: 'Pakistan', value: 'pakistan' },
  { label: 'Philippines', value: 'philippines' },
  { label: 'Malaysia', value: 'malaysia' },
  { label: 'UK', value: 'uk' },
  { label: 'Japan', value: 'japan' },
];

export const GENDER_LIST = [
  { label: 'Male', value: 'male' },
  { label: 'Female', value: 'female' },
];

