import mongoose, { Schema, Document, Model } from 'mongoose';

const BusinessProfileSchema: Schema = new Schema(
  {
    businessId: { type: String },
    name: { type: String, required: true },
    businessType: { type: String, required: true },
    businessDescription: { type: String },
    registrationNumber: { type: String },
    taxId: { type: String },
    establishedDate: { type: String },
    status: { type: String, required: true },
    primaryIndustry: { type: String, required: true },
    niche: { type: String, required: true },
    subNiche: { type: String, required: true },
    serviceName: { type: String, required: true },
    category: { type: String, required: true },
    subCategory: { type: String },
    serviceDescription: { type: String },
    pricingModel: {
      type: String,
      enum: ['Hourly', 'Fixed', 'Tiered', 'Subscription'],
      required: true,
    },
    rate: { type: String, required: true },
    currency: { type: String, required: true },
    serviceAvailability: {
      type: String,
      enum: ['Online', 'On-Site', 'Hybrid'],
      required: true,
    },
    onlineService: { type: String, enum: ['Yes', 'No'], required: true },
    street: { type: String },
    subCity: { type: String },
    city: { type: String, required: true },
    state: { type: String, required: true },
    postalCode: { type: String },
    country: { type: String, required: true },
    businessPhone: { type: String },
    secondaryPhone: { type: String },
    email: { type: String },
    supportEmail: { type: String },
    website: { type: String },
    keyContactName: { type: String },
    keyContactPosition: { type: String },
    keyContactDepartment: { type: String },
    keyContactPhone: { type: String },
    keyContactEmail: { type: String },
    keyContactLinkedIn: { type: String },
    opFacebook: { type: String },
    opInstagram: { type: String },
    opLinkedin: { type: String },
    opTwitter: { type: String },
    opYoutube: { type: String },
    opTiktok: { type: String },
    opGoogleBusiness: { type: String },
    opDirectoryListings: { type: String },
    operationsOpeningHours: { type: String },
    operationsTimeZone: { type: String },
    operationsEmployees: { type: String },
    operationsTools: { type: String },
    operationsCertifications: { type: String },
    fnPaymentMethods: { type: String },
    fnBillingAddress: { type: String },
    fnInvoiceContact: { type: String },
    fnPrimaryCurrency: { type: String },
    fnPaymentTerms: { type: String },
    legalLicenses: { type: String },
    legalPermits: { type: String },
    legalInsurance: { type: String },
    legalComplianceCertificates: { type: String },
    marketingTargetAudience: { type: String },
    marketingValueProposition: { type: String },
    marketingMainCompetitors: { type: String },
    marketingKeywords: { type: String },
    metaTags: { type: String },
    metaNotes: { type: String },
    metaDateAdded: { type: String },
    metaLastUpdated: { type: String },
  },
  { timestamps: true }
);

const BusinessProfile =
  mongoose.models.BusinessProfile ||
  mongoose.model('BusinessProfile', BusinessProfileSchema);

export default BusinessProfile;
